### PR TITLE
Fix command-line instruction $npm run-script dev

### PR DESCRIPTION
**Pull request by andyl**
When I tried to follow your command-line instruction, the command `$npm dev` didn't work for me.

But this command `$npm run-script dev` did work!!

I'm a total NodeJS newbie, so forgive me if I've overlooked something obvious!!  :-)

### CODE REVIEW

**Comment by radubrehar** [comment]
Hi Andyl and thanks for the PR.

Indeed, `npm dev` does not work. It should have read `npm run dev`.

`npm run <script-name>` is the preferred way (and shorter) of running scripts (instead of `npm run-script <script-name>` in the node community. Could you please update to this shorter form?

Thanks

**Comment by andyl** [comment]
@radubrehar - thanks for the tip - just made the update.

**Comment by radubrehar** [comment]
Thanks! Good job and welcome to the node/npm/frontend community!

**Comment by radubrehar** [comment]
Just released `1.2.4` on npm with the fix in the readme

**Pull request merged**
